
loadRefGenome <- function(organism.name) {
  library(Biostrings)
library(BiocManager)
library(biomaRt)
library(biomartr)
library(caret)
library(e1071)
library(kernlab)
library(pROC)
library(ROCR)
library(randomForest)
library(randomForestExplainer)
library(ggsignif)
library(quanteda)
library(reshape2)
library(ggplot2)
library(plyr)
library(ggpubr)
library(dplyr)
library(stringr)
library(rstatix)
library(randtests)
library(bench)
library(mcp)
library(tidyverse)
library(patchwork)
library(devtools)
library(Rbeast)
library(doParallel)
  genome.refseq <- getGenome(db = "refseq", organism = organism.name, path = file.path("_ncbi_downloads","genomes"))
  Genome <-  read_genome(file = genome.refseq)
  return(Genome)
}
